#!/usr/bin/env bash

set -Eeuo pipefail

# requires-apt-packages: postgresql postgresql-contrib

SCRIPT_DIR=$(
  cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd
)

bash "${SCRIPT_DIR}/install-required-apt-packages" "$0"
