#!/usr/bin/env bash

set -xeu

# with_all_md: Run a command on all Markdown (.md) files, excluding any found
# within .venv or node_modules directories at any level of the directory tree.
#
# Usage:
#   with_all_md <command> [args...]
#
# The command and arguments will be passed all Markdown files as positional arguments.
# Example:
#   with_all_md mdformat --number --wrap 80
#
with_all_md() {
  if [[ $# -eq 0 ]]; then
    echo "Usage: with_all_md <command> [args...]" >&2
    return 1
  fi
  fd --print0 \
   --type f \
   --extension md \
   --extension markdown \
   --extension mdx \
   . | xargs -0 "$@"
}

with_all_md mdtablefix --wrap --renumber --breaks --ellipsis --fences --in-place
with_all_md markdownlint --fix
