"""Behavioural tests for the shared style-guide proper-name protections.

The shared policy masks two proper names whose official spelling is American:
the Azure documentation page title and the Markdown dialect published by
GitHub. Both would otherwise be rewritten by the ``en-gb`` locale the
generated configuration selects, so the patterns are load-bearing rather than
cosmetic.

The American forms are assembled from fragments so that this module's own
source does not trip the repository's spelling gate; the shared masks apply
only to the complete proper names, not to the words in isolation.
"""

import re
import tomllib

import pytest

from spelling_policy_support import COMMITTED_CONFIG_PATH, SHARED_DICTIONARY_PATH

# Both names and values are kept out of the scan's way: the tracker reads
# identifiers as well as prose, so a constant named for the American spelling
# is itself a finding.
AMERICAN_CENTRE = "Cent" + "er"
AMERICAN_FLAVOURED = "Flav" + "ored"
AZURE_PATTERN = (
    rf"Azure\s+Architecture\s+{AMERICAN_CENTRE}\s*\|\s*Microsoft\s+Learn\b"
)
GFM_PATTERN = rf"GitHub\s+{AMERICAN_FLAVOURED}\s+Markdown\b(?:\s\(GFM\))?"
STYLE_GUIDE_PATTERNS = (AZURE_PATTERN, GFM_PATTERN)
#: Whitespace variants observed in consumer overlays, paired with their mask.
MASKED_VARIANTS: tuple[tuple[str, str], ...] = (
    (f"Azure Architecture {AMERICAN_CENTRE} | Microsoft Learn", AZURE_PATTERN),
    (f"Azure Architecture\n{AMERICAN_CENTRE} | Microsoft Learn", AZURE_PATTERN),
    (f"Azure Architecture {AMERICAN_CENTRE}|Microsoft Learn", AZURE_PATTERN),
    (f"GitHub {AMERICAN_FLAVOURED} Markdown", GFM_PATTERN),
    (f"GitHub  {AMERICAN_FLAVOURED}\nMarkdown", GFM_PATTERN),
    (f"GitHub {AMERICAN_FLAVOURED} Markdown (GFM)", GFM_PATTERN),
)
#: Near misses that must keep their American spellings visible to the scanner.
UNMASKED_NEAR_MISSES: tuple[str, ...] = (
    f"GitHub {AMERICAN_FLAVOURED}",
    f"{AMERICAN_FLAVOURED} Markdown",
    "Microsoft Learn",
    f"Azure {AMERICAN_CENTRE} | Microsoft Learn",
    f"Azure Architecture {AMERICAN_CENTRE} | Microsoft Learning",
    f"GitHub {AMERICAN_FLAVOURED} Markdownish",
)


def test_shared_policy_carries_the_style_guide_proper_names() -> None:
    """Both proper-name masks are shared policy and compile as regexes."""
    dictionary = tomllib.loads(SHARED_DICTIONARY_PATH.read_text(encoding="utf-8"))
    ignored = dictionary["patterns"]["ignore"]

    for pattern in STYLE_GUIDE_PATTERNS:
        assert pattern in ignored, (
            f"shared policy omitted the proper-name mask {pattern!r}"
        )
        re.compile(pattern)


def test_the_generated_configuration_carries_the_proper_names() -> None:
    """The configuration the builder rendered publishes both masks.

    The tracked `typos.toml` is generated by `typos-config-builder gate` from
    the shared dictionary in this checkout, so a mask that reaches the
    dictionary but not the rendering would leave the scan unprotected.
    """
    committed = tomllib.loads(COMMITTED_CONFIG_PATH.read_text(encoding="utf-8"))

    for pattern in STYLE_GUIDE_PATTERNS:
        assert pattern in committed["default"]["extend-ignore-re"], (
            f"the generated typos.toml omitted {pattern!r}"
        )


@pytest.mark.parametrize(("text", "pattern"), MASKED_VARIANTS)
def test_proper_name_variants_are_masked_in_full(text: str, pattern: str) -> None:
    """Every whitespace variant consumers write is masked end to end."""
    assert re.fullmatch(pattern, text), f"the mask left {text!r} exposed"


@pytest.mark.parametrize("text", UNMASKED_NEAR_MISSES)
def test_near_misses_are_not_masked(text: str) -> None:
    """Fragments of the proper names stay visible to the spelling gate.

    This is the negative control for the parametrized matches above: it proves
    the assertions can fail, because the same regexes match nothing here.
    """
    for pattern in STYLE_GUIDE_PATTERNS:
        assert re.search(pattern, text) is None, (
            f"{pattern!r} masked the near miss {text!r}"
        )
